# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-11 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andablog', '0005_auto_20151017_1747'),
        ('social_auth', '0005_auto_20160727_2333'),
        ('home', '0003_auto_20160920_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andablog.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='entry',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='instagrampointofinterest',
            name='poi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PointOfInterest'),
        ),
        migrations.AddField(
            model_name='instagrampointofinterest',
            name='user_social_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_auth.UserSocialAuth'),
        ),
        migrations.AddField(
            model_name='entrypointofinterest',
            name='poi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PointOfInterest'),
        ),
    ]
