# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-11 18:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161011_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampointofinterest',
            name='cached_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
