# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_instagrampointofinterest_cached_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PointOfInterest')),
            ],
        ),
    ]
